package(default_visibility = ["//visibility:public"])

load("//cpplint:cpplint.bzl", "cpplint")

cc_binary(
    name = "test_main",
    srcs = ["test_main.cc"],
    deps = ["//platforms"],
)

cpplint()
